# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonFromCSV
                                 A QGIS plugin
 Creates polygons from coordinates stored in CSV file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-14
        copyright            : (C) 2020 by Paweł Strzelewicz
        email                : aviationgisapp@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolygonFromCSV class from file PolygonFromCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygon_from_csv import PolygonFromCSV
    return PolygonFromCSV(iface)
